#RUN: ansible-playbook localhost-deploy.yaml -K --extra-vars "ansible_user=USERNAME"

#Replace USERNAME with the name of the operating system user that will execute the playbook.

- hosts: localhost
  connection: local

  # Roles to execute

  roles:

    # Package update and upgrade
    - {role: update-upgrade-packages}

    # Docker Installation
    - {role: docker-installation}


    # A swap space (2GB) is created if it does not exist
    - {role: add-swap-space}  

    # Installation of NodeJS and global packages using Node Version Manager (NVM)
    - {role: node-with-nvm, node_version: "10.19.0", angular_version: "9.1.13"}

    # Installation of MongoDB and configuration of users
    - {role: mongodb}

    - {role: mongodb_users}

    # Installation of NEURONE-Core
    - {role: NEURONE-Core, 
        build_neurone_core_on_server: true,
      }  

    # Installation of the neurone-gm (Server) module or API using pm2
    - {role: neurone-gm}

    # Installation of Trivia Server using pm2 and Trivia Client using Angular
    - {role: GAME-localhost, 
        # trivia_repository: "https://github.com/NEURONE-IL/GAME.git",
        trivia_repository: "https://github.com/trabajo-titulacion-neurone/neurone-trivia.git",
        build_trivia_frontend_on_server: true, #true if you want to build on remote server (2GB of ram required)
      }

    # Installation of Nginx
    - {role: nginx,
        http_connection: true,
        https_connection: false,
    }

  tasks: