# ---
# tasks file for NEURONE-Core
- name: Update apt and install ca-certificates
  become: true
  apt:
    name: ca-certificates
    state: latest
    update_cache: true

- name: Update apt and install curl
  become: true
  apt:
    name: curl
    state: latest
    update_cache: true

- name: Update apt and install gnupg
  become: true
  apt:
    name: gnupg
    state: latest
    update_cache: true

- name: Update apt and install lsb-release
  become: true
  apt:
    name: lsb-release
    state: latest
    update_cache: true

- name: Clone or update neurone core repository
  git:
    repo: "{{ neurone_repository }}"
    dest: "{{ neurone_directory }}"
    clone: yes
    update: yes
    force: yes

- name: Create directories in the file system
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ NEURONE_USERNAME }}"
    group: "{{ NEURONE_USERNAME }}"
    mode: '0755'
  loop:
    - "{{ NEURONE_ASSET_PATH }}"
    - "{{ NEURONE_MONGO_PATH }}"
    - "{{ NEURONE_INDEX_PATH }}"
  become: true

- name: Upload NEURONE-Core images from tar files
  ignore_errors: true
  ansible.builtin.shell: > 
    docker load --input neurone.tar
    docker load --input mongo.tar
  args:
    chdir: "{{ neurone_core_images_path }}"

- name: Build NEURONE-Core images with Docker Compose
  ignore_errors: true
  ansible.builtin.shell: docker-compose -p neurone build
  become: true
  args:
    executable: /bin/bash
    chdir: "{{ neurone_directory }}"
  when: build_neurone_core_on_server
  
- name: Start NEURONE-Core with Docker Compose
  ansible.builtin.shell:
  #docker compose -p neurone up --force-recreate -d
    cmd: |
      set -o allexport
      source {{ neurone_directory }}/dotenv
      set +o allexport
      docker compose -p neurone up -d
  become: true
  args:
    executable: /bin/bash
    chdir: "{{ neurone_directory }}"


















# - name: Start NEURONE with Docker Compose
#   ignore_errors: true
#   become: true
#   ansible.builtin.command: docker compose -p neurone up --force-recreate -d
#   args:
#     chdir: "{{ neurone_directory }}"


