

- hosts: webservers

  #Esto viene incluido con la ejecucion de los roles mongodb y mongodb_users
  become_user: root
  become_method: sudo
  roles:
    - update-upgrade-packages
    - docker-installation
    - nginx
    - node-with-nvm
    # - mongodb
    # - mongodb_users

    
  become: true
  serial: 1 # Cantidad de host en simultaneo en que se ejecutará el playbook
  tasks:

############## Instalacion y actualización de paquetes #################################################



# ################################# Instalacion y actualización de paquetes #############################





















  - name: Clone or update neurone-gm repositoryy
    git:
      repo: 'https://github.com/trabajo-titulacion-neurone/modulo-neurone-gm.git'
      dest: ~/escritorio/modulo-neurone-gm
      clone: yes
      update: yes

    # - name: Clonacion de un repositorio privado desde bash y un token (FUNCIONA. Borrar despues)
    #   shell: git clone https://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@github.com/gerardoluceroc/repo-privado.git /root/escritorio/repo-privado

  - name: Clone or update trivia GAME repositoryy
    git:
      repo: 'https://github.com/trabajo-titulacion-neurone/neurone-trivia.git'
      dest: ~/escritorio/neurone-trivia
      clone: yes
      update: yes









