

- hosts: webservers

  #Esto viene incluido con la ejecucion de los roles mongodb y mongodb_users
  become_user: root
  become_method: sudo
  roles:
    - node-with-nvm
    # - mongodb
    # - mongodb_users

    
  become: true
  serial: 1 #esto fue agregado junto con vars para las tareas que se usan para instalar docker
  vars:
    container_count: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d
  tasks:

############## Instalacion y actualización de paquetes #################################################
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes


  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest



 ######################## Instalacion de PM2 ##################################
  - name: Install PM2 packages
    #become: yes
    npm:
      executable: ~/.nvm/versions/node/v16.14.1/bin/npm #QUEDA PENDIENTE PASAR EL v16.14.1 como variable o constante global
      name: pm2
      global: yes
      state: present
###############################################################################











##################### Instalacion de http-server ###################################################33
  - name: Install http-server (OPCIONAL)
    npm:
      executable: ~/.nvm/versions/node/v16.14.1/bin/npm #QUEDA PENDIENTE PASAR EL v16.14.1 como variable o constante global
      name: http-server
      global: yes
      state: present
  
#####################################################################################################












###################################### Instalacion de Docker (Fuente: https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04)
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

###################################### FIN Instalacion de docker #########################################################












############################# Instalacion y activacion de nginx ###########################################################
  - name: install and check nginx latest version
    apt:
      name: nginx
      state: latest
  
  - name: start nginx
    service:
      name: nginx
      state: started

#############################################################################################################################




################################# Instalacion y actualización de paquetes #############################################################





















  - name: Clone or update neurone-gm repositoryy
    git:
      repo: 'https://github.com/trabajo-titulacion-neurone/modulo-neurone-gm.git'
      dest: ~/escritorio/modulo-neurone-gm
      clone: yes
      update: yes

    # - name: Clonacion de un repositorio privado desde bash y un token (FUNCIONA. Borrar despues)
    #   shell: git clone https://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@github.com/gerardoluceroc/repo-privado.git /root/escritorio/repo-privado

  - name: Clone or update trivia GAME repositoryy
    git:
      repo: 'https://github.com/trabajo-titulacion-neurone/neurone-trivia.git'
      dest: ~/escritorio/neurone-trivia
      clone: yes
      update: yes









