- hosts: webservers

  #Esto viene incluido con la ejecucion de los roles mongodb y mongodb_users
  become_user: root
  become_method: sudo
  roles:
    - add-swap-space
    - update-upgrade-packages
    - docker-installation
    - nginx
    - node-with-nvm
    - mongodb
    - mongodb_users
    - GAME
    - neurone-gm

  become: true
  serial: 1 # Cantidad de host en simultaneo en que se ejecutará el playbook
  tasks:

