---

- name: Crear usuario root en mongoO
  ignore_errors: true #esto se agrega ya que al ejecutar por segunda vez esta tarea se requiere autenticarse con el mismo usuario creado anteriormente, lo cual es redundante e innecesario. Por lo que en caso de haber un error, este se ignora.
  community.mongodb.mongodb_user:

    #Estas lineas deben agregarse en caso de querer actualizar los datos de un usuario root o agregar uno nuevo
    #Hay que loguearse con los datos de un usuario root existente
    # login_user: gerardo
    # login_password: gerardo321
    # login_port: 27017
    database: "{{ admin_database }}"
    name: "{{ mongodb_root_user }}"
    password: "{{ mongodb_root_password }}"
    #roles: readWrite,dbAdmin,userAdmin
    roles: root
    state: present

- name: Create neuroneAdmin user
  community.mongodb.mongodb_user:

    login_user: "{{ mongodb_root_user }}"
    login_password: "{{ mongodb_root_password }}"
    database: "{{ admin_database }}"
    name: "{{ mongodb_admin_user }}"
    password: "{{ mongodb_admin_password }}"
    roles: userAdminAnyDatabase,readWriteAnyDatabase 
    state: present
