---
# tasks file for node-with-nvm
#Instalación y activación de una version especifica de nodejs utilizando Node Package Manager

  ########################## Instalacion de Node con NVM #####################################################################################
# - name: Run the equivalent of "apt-get update" as a separate step
#   apt:
#     update_cache: yes

# - name: Update all packages to the latest version
#   apt:
#     upgrade: dist

# - name: Upgrade all packages to the latest version
#   apt:
#     name: "*"
#     state: latest

- name: Install NVM (Node Version Manager) #Fuente: https://gist.github.com/komuw/b3b5d24977d4df7bd549
  become: false
  ansible.builtin.shell: > # Usar el módulo "shell" para ejecutar comandos de shell e instalar nvm desde el script
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash # Indicar que el shell a utilizar es Bash
    chdir: "$HOME" # Cambiar el directorio de trabajo al directorio de inicio del usuario
    creates: "$HOME/.nvm/nvm.sh" # Se comprueba si el archivo "nvm.sh" ya existe en el directorio de inicio

- name: Install Node 
  become: true
  shell: > # Activar nvm y luego instalar una versión específica de Node.js y dejarla activada por defecto
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }} && nvm alias default {{ node_version }}

  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
  
  loop: # Realizar esta tarea para múltiples versiones de Node.js
    - "{{ node_version }}" 

#Para que esto funcione hay que ejecutar el siguiente comando en el server para crear un enlace simbolico con la version por defecto de node que se esta usando
- name: Activar Node con link simbolico
  become: true
  shell: >
    ln -sf ~/.nvm/versions/node/v{{ node_version }}/bin/node /usr/bin/node
    

- name: Install PM2 packages
  become: false
  npm:
    executable: ~/.nvm/versions/node/v{{ node_version }}/bin/npm
    name: pm2
    global: yes
    state: present

- name: Install http-server (OPCIONAL)
  npm:
    executable: ~/.nvm/versions/node/v{{ node_version }}/bin/npm
    name: http-server
    global: yes
    state: present


  ########################## FIN Instalacion de Node con NVM #####################################################################################
