---
# tasks file for NEURONE-Core
  # - name: Update apt and install ca-certificates
  #   become: true
  #   apt:
  #     name: ca-certificates
  #     state: latest
  #     update_cache: true

  # - name: Update apt and install curl
  #   become: true
  #   apt:
  #     name: curl
  #     state: latest
  #     update_cache: true

  # - name: Update apt and install gnupg
  #   become: true
  #   apt:
  #     name: gnupg
  #     state: latest
  #     update_cache: true

  # - name: Update apt and install lsb-release
  #   become: true
  #   apt:
  #     name: lsb-release
  #     state: latest
  #     update_cache: true

  # - name: Clone or update neurone core repository
  #   git:
  #     repo: "{{ neurone_repository }}"
  #     dest: "{{ neurone_directory }}"
  #     clone: yes
  #     update: yes
  #     # force: yes

  # - name: Create neuroneAssets folder if not exist
  #   ansible.builtin.file:
  #     path: "{{ ansible_env.HOME }}/neuroneAssets"
  #     state: directory

  # - name: Create neuroneDatabase folder if not exist
  #   ansible.builtin.file:
  #     path: "{{ ansible_env.HOME }}/neuroneDatabase"
  #     state: directory

  # - name: build neurone
  #   # become: true
  #   # become_user: root
  #   ansible.builtin.script: "{{ neurone_directory }}/neurone-build.sh"
  #   # args:
  #   #   chdir: "{{ neurone_directory }}"





- name: Crear directorios en el sistema de archivos
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ NEURONE_USERNAME }}"
    group: "{{ NEURONE_USERNAME }}"
    mode: '0755'
  loop:
    - "{{ NEURONE_ASSET_PATH }}"
    - "{{ NEURONE_MONGO_PATH }}"
    - "{{ NEURONE_INDEX_PATH }}"
  become: true

- name: Construir imágenes de implementación de NEURONE con Docker Compose
  ansible.builtin.command: "docker-compose -p neurone build"
  become: true
  args:
    chdir: "{{ neurone_directory }}"
























  # - name: Build NEURONE-Core with shell script
  #   become: true
  #   ansible.builtin.shell: "./neurone-build.sh"
  #   args:
  #     chdir: "{{neurone_directory}}"
  
  # - name: Start NEURONE-Core with shell script
  #   become: true
  #   ansible.builtin.shell: "./neurone-start.sh"
  #   args:
  #     chdir: "{{neurone_directory}}"



