---
# defaults file for NEURONE-Core
NEURONE_USERNAME: "{{ ansible_user }}"
NEURONE_USERID: ""

neurone_repository: "https://github.com/NEURONE-IL/neurone.git"
neurone_directory: "{{ ansible_env.HOME }}/apps/neurone-master"
build_neurone_core_on_server: false
neurone_core_images_path: "{{ ansible_env.HOME }}/neurone-images"