---
# tasks file for nginx

- name: install and check nginx latest version
  become: true
  apt:
    name: nginx
    state: latest

- name: Install core snap
  become: true
  community.general.snap:
    name: core
    state: present

- name: Install certbot snap
  become: true
  community.general.snap:
    name: certbot
    classic: true
    state: present

- name:  Link the certbot command from the snap install directory 
  become: true
  ansible.builtin.shell: ln -sf /snap/bin/certbot /usr/bin/certbot

- name: Get SSL/TLS certificate with Certbot
  become: true
  ansible.builtin.shell: certbot --nginx -d neurone-trivia.lat -d www.neurone-trivia.lat --agree-tos --non-interactive --email gerardoluceroc@gmail.com

- name: Copy Nginx configuration file
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/templates/game_https.conf"
    dest: /etc/nginx/sites-available/game_https.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"     
    mode: 0644
  notify:
    - Reload Nginx

- name: Activate Game config
  become: true
  ansible.builtin.shell: ln -sf /etc/nginx/sites-available/game_https.conf /etc/nginx/sites-enabled/
  notify:
  - Reload Nginx

- name: Desactivate default config
  become: true
  ignore_errors: true
  ansible.builtin.shell: rm /etc/nginx/sites-enabled/default
  notify:
  - Reload Nginx

- name: start nginx
  ignore_errors: true
  become: true
  ansible.builtin.service:
    name: nginx
    state: started