---
# tasks file for nginx

- name: install and check nginx latest version
  become: true
  apt:
    name: nginx
    state: latest

- name: Copy Nginx configuration file
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/templates/game_http.conf"
    dest: /etc/nginx/sites-available/game_http.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"     
    mode: 0644
  notify:
    - Reload Nginx

# - name: Activate Game config
#   ansible.builtin.file:
#     src: /etc/nginx/sites-available/game_http.conf
#     dest: /etc/nginx/sites-enabled/
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     state: link
#   notify:
#   - Reload Nginx

- name: Activate Game config
  become: true
  ansible.builtin.shell: ln -sf /etc/nginx/sites-available/game_http.conf /etc/nginx/sites-enabled/
  notify:
  - Reload Nginx

- name: Desactivate default config
  become: true
  ignore_errors: true
  ansible.builtin.shell: rm /etc/nginx/sites-enabled/default
  notify:
  - Reload Nginx

- name: start nginx
  ignore_errors: true
  become: true
  ansible.builtin.service:
    name: nginx
    state: started