---
# defaults file for nginx


################ TRIVIA CONFIG DATA ############################

#If true, nginx will be configured with the game_http.conf file which sets up a server with an HTTP connection
trivia_http_connection: false
trivia_http_config_file: "{{ role_path }}/templates/game_http.conf"




#If true, nginx will be configured with the game_https.conf file which sets up a server with an HTTPS connection
trivia_https_connection: true
trivia_https_config_file: "{{ role_path }}/templates/game_https.conf"
trivia_domain_name: "neurone-trivia.lat" 
email: "gerardoluceroc@gmail.com" #Email associated with the declared domain


################ TRAINER CONFIG DATA ############################


#If true, nginx will be configured with the trainer_http.conf file which sets up a server with an HTTP connection
trainer_http_connection: false
trainer_http_config_file: "{{ role_path }}/templates/trainer_http.conf"




#If true, nginx will be configured with the trainer_https.conf file which sets up a server with an HTTPS connection
trainer_https_connection: true
trainer_https_config_file: "{{ role_path }}/templates/trainer_https.conf"
trainer_domain_name: "neurone-trainer.lat" 