- name: Install and configure MongoDB on Ubuntu 22.04 
  hosts: all
  become_user: root
  become_method: sudo
  become: true
  roles:
    - mongodb
    - mongodb_users
    
    
    
#Fuente: https://shreedhar1998.hashnode.dev/automating-mongodb-installation-across-multiple-servers-using-ansible-roles-jenkins

#https://github.com/sridhar-modalavalasa/Ansible-Mongodb-roles
