---
# tasks file for docker-installation
# ###################################### Docker Installation (Source: https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04)
  - name: Add Docker GPG apt Key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    become: true
    apt:
      name: docker-ce
      state: latest
      update_cache: true

# Dependencies for NEURONE core

  - name: Update apt and install docker-ce-cli
    become: true
    apt:
      name: docker-ce-cli
      state: latest
      update_cache: true

  - name: Update apt and install containerd.io
    become: true
    apt:
      name: containerd.io
      state: latest
      update_cache: true

  - name: Update apt and install docker-compose
    become: true
    apt:
      name: docker-compose
      state: latest
      update_cache: true

  - name: Enable using Docker for current user (without requiring sudo)
    become: true
    ansible.builtin.shell: usermod -aG docker $(whoami)

  - name: Restart Docker service
    become: true
    ansible.builtin.systemd_service:
      name: docker
      state: restarted