---
# defaults file for neurone-gm
neuronegm_repository: "https://github.com/gerardoluceroc/NEURONE-GM.git"


#Path where the neurone-gm repository will be stored both on the server and on the local machine where the playbook runs in case if is necessary to clone it.
neuronegm_directory: "{{ ansible_env.HOME }}/apps/NEURONE-GM"

#Path where the neurone-gm Server folder will be stored
neuronegm_server_directory: "{{ ansible_env.HOME }}/apps/NEURONE-GM/Server"

#Name of the pm2 process running neuronegm server will have.
neuronegm_server_pm2_process_name: "Neuronegm-Server"


#neurone-gm configuration file will be replaced by the one located inside the role's files directory

#The neurone-gm configuration file will be replaced by the one found inside the role's "files" directory
neuronegm_server_config_file_localhost: "{{ role_path }}/files/config.js"

#Path of the file that will be replaced by the file which is in the role's directory
neuronegm_server_config_file_remote_server: "{{ ansible_env.HOME }}/apps/NEURONE-GM/Server/config/config.js"

