---
# tasks file for reboot-and-wait

# Task to restart the server
- name: Restart server
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 600  # Timeout in seconds, adjust as needed
  async: 0
  poll: 0
  register: reboot_result
  ignore_errors: true

# Task to check if the server has come back online
- name: Wait for server to come back online
  become: true
  ansible.builtin.wait_for_connection:
    timeout: 360  # Timeout in seconds, adjust as needed
  when: reboot_result.rebooted
