---
# - name: Create MongoDB root userr
#   mongodb_user:
#     #state: present #linea agregada por gerardo
#     login_port: "27017"
#     database: "admin"
#     name: "{{ mongodb_root_user }}"
#     password: "{{ mongodb_root_password }}"
#     roles: "root"

# - name: Create MongoDB administrative user siteUserAdmin
#   mongodb_user:
#     login_user: "{{ mongodb_root_user }}"
#     login_password: "{{ mongodb_root_password }}"
#     login_port: "27017"
#     database: "{{ database_name }}"
#     name: "{{ mongodb_admin_user }}"
#     password: "{{ mongodb_admin_password }}"
#     roles:
#       - { db: "admin", role: "readWrite" }
#       - { db: "{{ database_name }}", role: "readWrite" }

# - name: Create MongoDB backup user siteUserBackup
#   mongodb_user:
#     login_user: "{{ mongodb_root_user }}"
#     login_password: "{{ mongodb_root_password }}"
#     login_port: "27017"
#     database: "{{ database_name }}"
#     name: "{{ mongodb_backup_user }}"
#     password: "{{ mongodb_backup_password }}"
#     roles:
#       - { db: "admin", role: "backup" }




########### CODIGO MIOOO ############################3

- name: Crear usuario root en mongoO
  community.mongodb.mongodb_user:

    #Estas lineas deben agregarse en caso de querer actualizar los datos de un usuario root o agregar uno nuevo
    #Hay que loguearse con los datos de un usuario root existente
    #login_user: gerardo
    #login_password: gerardo321
    #login_port: 27017

    database: admin
    name: gerardo
    password: gerardo321
    #roles: readWrite,dbAdmin,userAdmin
    roles: root
    state: present

#- name: Crear usuario administrador en mongo
