---
# tasks file for GAME

- name: Node version being used is loaded for linking with nvm
  ansible.builtin.include_vars:
    file: roles/node-with-nvm/vars/main.yml
    name: node_vars


- name: Clone or update trivia repository
  git:
    repo: "{{ trivia_repository }}"
    dest: "{{ trivia_directory }}"
    clone: yes
    update: yes
    force: yes #This is added due to an issue with modifying the package-lock.json in the local repository.




- name: Install trivia-client dependencies.
  community.general.npm:
    path: "{{ trivia_client_directory }}"
    executable: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_vars.node_version }}/bin/npm"

# - name: Build Frontend
#   become: true
#   ansible.builtin.command: ng build --prod --output-path ../Server/public
#   args:
#     chdir: "{{ trivia_client_directory }}"



- name: Install trivia-server dependencies.
  community.general.npm:
    path: "{{ trivia_server_directory }}"
    executable: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_vars.node_version }}/bin/npm"

#Saved processes are restored in case of a server reboot
- name: pm2 resurrect
  ansible.builtin.command: pm2 resurrect

- name: Run the command "pm2 ls"
  ansible.builtin.command: pm2 ls
  register: pm2_processes

- name: Analyse the output looking for the 'trivia-server' process
  #The boolean response is stored in the variable 'running_process'.
  ansible.builtin.set_fact:
    running_process: "{{ trivia_server_pm2_process_name in pm2_processes.stdout }}"


- name: Execute the PM2 command (restart) if the process is running
  ansible.builtin.command: pm2 restart {{ trivia_server_pm2_process_name }}
  args:
    chdir: "{{ trivia_server_directory }}"
  when: running_process

- name: Execute the PM2 command (start) if the process is not running or not created.
  ansible.builtin.command: pm2 start app.js --name {{ trivia_server_pm2_process_name }}
  args:
    chdir: "{{ trivia_server_directory }}"
  when: not running_process

# Save current process list
- name: pm2 save
  ansible.builtin.command: pm2 save


